const RIVER_CATALOG = [
    {"file": "CPT_River_End_L_a_01.fbx", "rot": 0, "type": "river_end", "sockets": { "S": "POS_A" }},
    {"file": "CPT_River_End_L_a_01.fbx", "rot": 1, "type": "river_end", "sockets": { "E": "POS_B" }},
    {"file": "CPT_River_End_L_a_01.fbx", "rot": 2, "type": "river_end", "sockets": { "N": "POS_B" }},
    {"file": "CPT_River_End_L_a_01.fbx", "rot": 3, "type": "river_end", "sockets": { "W": "POS_A" }},
    {"file": "CPT_River_End_L_a_01_R.fbx", "rot": 0, "type": "river_end", "sockets": { "S": "POS_B" }},
    {"file": "CPT_River_End_L_a_01_R.fbx", "rot": 1, "type": "river_end", "sockets": { "E": "POS_A" }},
    {"file": "CPT_River_End_L_a_01_R.fbx", "rot": 2, "type": "river_end", "sockets": { "N": "POS_A" }},
    {"file": "CPT_River_End_L_a_01_R.fbx", "rot": 3, "type": "river_end", "sockets": { "W": "POS_B" }},
    {"file": "CPT_River_End_L_c_01.fbx", "rot": 2, "type": "mouth", "sockets": { "N": "POS_B" }},
    {"file": "CPT_River_End_L_c_01_R.fbx", "rot": 2, "type": "mouth", "sockets": { "N": "POS_A" }},
    {"file": "CPT_River_End_L_c_02.fbx", "rot": 2, "type": "mouth", "sockets": { "N": "POS_B" }},
    {"file": "CPT_River_End_L_c_02_R.fbx", "rot": 2, "type": "mouth", "sockets": { "N": "POS_A" }},
    {"file": "CPT_River_L_a_01.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_A" }},
    {"file": "CPT_River_L_a_01.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_B" }},
    {"file": "CPT_River_L_a_01.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_B" }},
    {"file": "CPT_River_L_a_01.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_a_01_R.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_B" }},
    {"file": "CPT_River_L_a_01_R.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_a_01_R.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_A" }},
    {"file": "CPT_River_L_a_01_R.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_B" }},
    {"file": "CPT_River_L_a_02.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_A" }},
    {"file": "CPT_River_L_a_02.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_B" }},
    {"file": "CPT_River_L_a_02.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_B" }},
    {"file": "CPT_River_L_a_02.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_a_02_R.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_B" }},
    {"file": "CPT_River_L_a_02_R.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_a_02_R.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_A" }},
    {"file": "CPT_River_L_a_02_R.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_B" }},
    {"file": "CPT_River_L_a_03.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_A" }},
    {"file": "CPT_River_L_a_03.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_B" }},
    {"file": "CPT_River_L_a_03.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_B" }},
    {"file": "CPT_River_L_a_03.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_a_03_R.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_B" }},
    {"file": "CPT_River_L_a_03_R.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_a_03_R.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_A" }},
    {"file": "CPT_River_L_a_03_R.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_B" }},
    {"file": "CPT_River_L_a_04.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_A" }},
    {"file": "CPT_River_L_a_04.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_B" }},
    {"file": "CPT_River_L_a_04.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_B" }},
    {"file": "CPT_River_L_a_04.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_a_04_R.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_B" }},
    {"file": "CPT_River_L_a_04_R.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_a_04_R.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_A" }},
    {"file": "CPT_River_L_a_04_R.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_B" }},
    {"file": "CPT_River_L_b_01.fbx", "rot": 0, "type": "curve", "sockets": { "S": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_b_01.fbx", "rot": 1, "type": "curve", "sockets": { "N": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_b_01.fbx", "rot": 2, "type": "curve", "sockets": { "N": "POS_B", "W": "POS_B" }},
    {"file": "CPT_River_L_b_01.fbx", "rot": 3, "type": "curve", "sockets": { "S": "POS_B", "W": "POS_A" }},
    {"file": "CPT_River_L_b_01_R.fbx", "rot": 0, "type": "curve", "sockets": { "S": "POS_B", "W": "POS_A" }},
    {"file": "CPT_River_L_b_01_R.fbx", "rot": 1, "type": "curve", "sockets": { "S": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_b_01_R.fbx", "rot": 2, "type": "curve", "sockets": { "N": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_b_01_R.fbx", "rot": 3, "type": "curve", "sockets": { "N": "POS_B", "W": "POS_B" }},
    {"file": "CPT_River_L_b_02.fbx", "rot": 0, "type": "curve", "sockets": { "S": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_b_02.fbx", "rot": 1, "type": "curve", "sockets": { "N": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_b_02.fbx", "rot": 2, "type": "curve", "sockets": { "N": "POS_B", "W": "POS_B" }},
    {"file": "CPT_River_L_b_02.fbx", "rot": 3, "type": "curve", "sockets": { "S": "POS_B", "W": "POS_A" }},
    {"file": "CPT_River_L_b_02_R.fbx", "rot": 0, "type": "curve", "sockets": { "S": "POS_B", "W": "POS_A" }},
    {"file": "CPT_River_L_b_02_R.fbx", "rot": 1, "type": "curve", "sockets": { "S": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_b_02_R.fbx", "rot": 2, "type": "curve", "sockets": { "N": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_b_02_R.fbx", "rot": 3, "type": "curve", "sockets": { "N": "POS_B", "W": "POS_B" }},
    {"file": "CPT_River_L_b_03.fbx", "rot": 0, "type": "curve", "sockets": { "S": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_b_03.fbx", "rot": 1, "type": "curve", "sockets": { "N": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_b_03.fbx", "rot": 2, "type": "curve", "sockets": { "N": "POS_B", "W": "POS_B" }},
    {"file": "CPT_River_L_b_03.fbx", "rot": 3, "type": "curve", "sockets": { "S": "POS_B", "W": "POS_A" }},
    {"file": "CPT_River_L_b_03_R.fbx", "rot": 0, "type": "curve", "sockets": { "S": "POS_B", "W": "POS_A" }},
    {"file": "CPT_River_L_b_03_R.fbx", "rot": 1, "type": "curve", "sockets": { "S": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_b_03_R.fbx", "rot": 2, "type": "curve", "sockets": { "N": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_b_03_R.fbx", "rot": 3, "type": "curve", "sockets": { "N": "POS_B", "W": "POS_B" }},
    {"file": "CPT_River_L_b_04.fbx", "rot": 0, "type": "curve", "sockets": { "S": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_b_04.fbx", "rot": 1, "type": "curve", "sockets": { "N": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_b_04.fbx", "rot": 2, "type": "curve", "sockets": { "N": "POS_B", "W": "POS_B" }},
    {"file": "CPT_River_L_b_04.fbx", "rot": 3, "type": "curve", "sockets": { "S": "POS_B", "W": "POS_A" }},
    {"file": "CPT_River_L_b_04_R.fbx", "rot": 0, "type": "curve", "sockets": { "S": "POS_B", "W": "POS_A" }},
    {"file": "CPT_River_L_b_04_R.fbx", "rot": 1, "type": "curve", "sockets": { "S": "POS_A", "E": "POS_A" }},
    {"file": "CPT_River_L_b_04_R.fbx", "rot": 2, "type": "curve", "sockets": { "N": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_b_04_R.fbx", "rot": 3, "type": "curve", "sockets": { "N": "POS_B", "W": "POS_B" }},
    {"file": "CPT_River_L_c_01.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_A" }},
    {"file": "CPT_River_L_c_01.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_c_01.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_A" }},
    {"file": "CPT_River_L_c_01.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_c_01_R.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_B" }},
    {"file": "CPT_River_L_c_01_R.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_A" }},
    {"file": "CPT_River_L_c_01_R.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_B" }},
    {"file": "CPT_River_L_c_01_R.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_A" }},
    {"file": "CPT_River_L_c_02.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_A" }},
    {"file": "CPT_River_L_c_02.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_c_02.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_B", "S": "POS_A" }},
    {"file": "CPT_River_L_c_02.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_A", "E": "POS_B" }},
    {"file": "CPT_River_L_c_02_R.fbx", "rot": 0, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_B" }},
    {"file": "CPT_River_L_c_02_R.fbx", "rot": 1, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_A" }},
    {"file": "CPT_River_L_c_02_R.fbx", "rot": 2, "type": "straight", "sockets": { "N": "POS_A", "S": "POS_B" }},
    {"file": "CPT_River_L_c_02_R.fbx", "rot": 3, "type": "straight", "sockets": { "W": "POS_B", "E": "POS_A" }},
]
